export const courseStyles = {
    courseContainer: {
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 12,
      },
      shadowOpacity: 0.58,
      shadowRadius: 16.00,
      elevation: 24,
      backgroundColor: 'white',
      display: 'flex',
      alignSelf: 'center',
      width: '85%',
      height: '91%',
      marginTop: 30,
    },
    courseItem: {
      marginTop: 40,
      display: 'flex',
      alignSelf: 'center',
      width: '88%',
      height: 130,
      border: 1,
      borderWidth: 1,
      borderColor: 'rgba(226,226,226,255)',
    },
    courseHeader: {
      height: '50%',
      backgroundColor: 'rgb(0, 174, 255)',
    },
    semesterBadge: {
      backgroundColor: 'rgba(222,149,0,255)',
      alignSelf: 'flex-end',
      padding: 2,
      width: 80,
      borderRadius: 2,
      height: 21,
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'center',
    },
    courseHeaderText: {
      color: 'white',
      fontWeight: 'bold',
      marginLeft: 20,
      fontSize: 16,
      position: 'relative',
      bottom: 4,
    },
    courseInfo: {
      color: 'white',
      fontWeight: 'bold',
      marginLeft: 20,
      fontSize: 11,
      position: 'relative',
      bottom: 4,
    },
    attendanceContainer: {
      height: '50%',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    },
    attendanceText: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'flex-start',
      width: '85%',
    },
    activityIndicator: {
      position: 'absolute',
      top: '50%',
      left: '50%',
    },
  };
  